name: RankPoints
main: JD\RankPoints\Main
version: 1.5.3
api: [3.0.0]
author: JD
load: POSTWORLD
commands:
  rankpoints:
    description: "Shows/Gives Rank Points"
    usage: "/rankpoints {player points}"
    
    