name: RankPoints
main: JD\RankPoints\Main
version: 1.5.2-2
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
author: JD
load: POSTWORLD
commands:
  rankpoints:
    description: "Shows/Gives Rank Points"
    usage: "/rankpoints {player points}"
    
    